#!/usr/bin/env tclsh
# ---------------------------------------------------------------------------
# File   : tr_sens_char.tcl
# Author : yoobeom.kim@samsung.com
# Purpose: Simulation driver of the LVF-sensitivity based global variation
#          flow.
#   -mode sens   : nominal + (each transistor x param x +/-delta)
#                  [+ each group x param x +/-delta when cfg(group_sens)=1]
#                  -> <out>/sens.csv, <out>/nominal.csv, <out>/devices.csv
#   -mode corner : direct simulation with every transistor of a group shifted
#                  by the corner definition (validation reference)
#                  -> <out>/corner_<name>.csv
# Usage  :
#   tclsh tr_sens_char.tcl -cfg example.cfg.tcl -mode sens [-cells {INV_X1}] [-jobs 8]
#   tclsh tr_sens_char.tcl -cfg example.cfg.tcl -mode corner -corner corners.tcl [-names {SSG FFG}]
#   -gen_only  : write decks and <out>/run_<mode>.sh only (farm submission)
#   -skip_sim  : do not simulate, parse existing results
#   -out <dir> : override cfg(out_dir)
# ---------------------------------------------------------------------------
set script_dir [file dirname [file normalize [info script]]]
source [file join $script_dir lvfgv_common.tcl]

namespace eval ::tsc {
    variable sens_header {cell arc meas slew_idx load_idx slew load inst group param delta sigma_mm v0 vplus vminus s1 s2}
    variable nom_header  {cell arc meas slew_idx load_idx slew load v0}
    variable cor_header  {cell arc meas slew_idx load_idx slew load corner v0 v_sim dv dv_rel}
    variable dev_header  {cell inst model group w l nf m sigma_mm_vth sigma_mm_u0}
}

# ---------------------------------------------------------------------------
proc ::tsc::usage {} {
    puts stderr "usage: tclsh tr_sens_char.tcl -cfg <cfg.tcl> -mode sens|corner \[-corner <corners.tcl>\]"
    puts stderr "         \[-names <corner list>\] \[-cells <cell list>\] \[-jobs N\] \[-out <dir>\] \[-gen_only\] \[-skip_sim\]"
    exit 1
}

# States of the sensitivity run for one cell:
#   list of {state pstate inst group param sign}
proc ::tsc::sens_states {devs} {
    set states [list [list nominal [dict create] "" "" "" 0]]
    foreach dev $devs {
        set inst [dict get $dev inst]
        set grp  [dict get $dev group]
        foreach p $::lvfgv::cfg(params) {
            foreach sign {1 -1} {
                set tag [expr {$sign > 0 ? "p" : "m"}]
                set v [::lvfgv::hook_value $p [expr {$sign * $::lvfgv::cfg(delta,$p)}] $grp]
                lappend states [list "${inst}_${p}_${tag}" \
                    [dict create [::lvfgv::pname $p $inst] $v] $inst $grp $p $sign]
            }
        }
    }
    if {$::lvfgv::cfg(group_sens)} {
        set groups {}
        foreach dev $devs {
            set g [dict get $dev group]
            if {$g ni $groups} { lappend groups $g }
        }
        foreach g $groups {
            foreach p $::lvfgv::cfg(params) {
                foreach sign {1 -1} {
                    set tag [expr {$sign > 0 ? "p" : "m"}]
                    set v [::lvfgv::hook_value $p [expr {$sign * $::lvfgv::cfg(delta,$p)}] $g]
                    set ps [dict create]
                    foreach dev $devs {
                        if {[dict get $dev group] eq $g} {
                            dict set ps [::lvfgv::pname $p [dict get $dev inst]] $v
                        }
                    }
                    lappend states [list "GROUP_${g}_${p}_${tag}" $ps "GROUP:$g" $g $p $sign]
                }
            }
        }
    }
    return $states
}

# State of a direct corner simulation
proc ::tsc::corner_state {devs shifts} {
    set ps [dict create]
    foreach dev $devs {
        set g [dict get $dev group]
        foreach p $::lvfgv::cfg(params) {
            if {[dict exists $shifts "$g,$p"]} {
                dict set ps [::lvfgv::pname $p [dict get $dev inst]] \
                    [::lvfgv::hook_value $p [dict get $shifts "$g,$p"] $g]
            }
        }
    }
    return $ps
}

# Generate decks for a list of states: returns dict state -> result file, and
# appends the simulation commands to cmdsVar.
proc ::tsc::gen_states {cell arc states subtext params ports cmdsVar} {
    upvar $cmdsVar cmds
    set arcname [dict get $arc name]
    set ddir [file join $::lvfgv::cfg(out_dir) decks $cell $arcname]
    set resmap [dict create]
    foreach st $states {
        lassign $st sname pstate
        set deck [file join $ddir "$sname$::lvfgv::cfg(deck_ext)"]
        ::lvfgv::gen_deck $deck $cell $arc $sname $pstate $subtext $params $ports
        lassign [::lvfgv::sim_paths $deck] cmd res log
        lappend cmds $cmd
        dict set resmap $sname $res
    }
    return $resmap
}

proc ::tsc::write_run_script {file cmds} {
    set fh [open $file w]
    puts $fh "#!/bin/sh"
    puts $fh "# simulation commands generated by tr_sens_char.tcl"
    foreach c $cmds { puts $fh $c }
    close $fh
    catch {file attributes $file -permissions 0755}
}

# Measures of one result file: dict meas,j,k -> value ("" when missing)
proc ::tsc::read_point_results {res} {
    set m [::lvfgv::parse_measures $res]
    set d [dict create]
    set nslew [llength $::lvfgv::cfg(slews)]
    set nload [llength $::lvfgv::cfg(loads)]
    for {set j 0} {$j < $nslew} {incr j} {
        for {set k 0} {$k < $nload} {incr k} {
            foreach {meas key} [list delay d_${j}_${k} trans s_${j}_${k}] {
                set v ""
                if {[dict exists $m $key] && [::lvfgv::is_num [dict get $m $key]]} {
                    set v [dict get $m $key]
                }
                dict set d "$meas,$j,$k" $v
            }
        }
    }
    return $d
}

# ---------------------------------------------------------------------------
proc ::tsc::main {argv} {
    variable sens_header
    variable nom_header
    variable cor_header
    variable dev_header
    set opt [::lvfgv::parse_args $argv {cfg mode corner names cells jobs out} {gen_only skip_sim}]
    if {![dict exists $opt cfg] || ![dict exists $opt mode]} { usage }
    ::lvfgv::load_cfg [dict get $opt cfg]
    if {[dict exists $opt out]} { set ::lvfgv::cfg(out_dir) [file normalize [dict get $opt out]] }
    if {[dict exists $opt jobs]} { set ::lvfgv::cfg(jobs) [dict get $opt jobs] }
    set mode [dict get $opt mode]
    if {$mode ni {sens corner}} { usage }
    set cells $::lvfgv::cfg(cells)
    if {[dict exists $opt cells]} { set cells [dict get $opt cells] }
    set outdir $::lvfgv::cfg(out_dir)
    file mkdir $outdir

    set cnames {}
    if {$mode eq "corner"} {
        if {![dict exists $opt corner]} { ::lvfgv::die "-mode corner needs -corner <corners.tcl>" }
        ::lvfgv::load_corners [dict get $opt corner]
        set cnames [::lvfgv::corner_names]
        if {[dict exists $opt names]} { set cnames [dict get $opt names] }
        if {[llength $cnames] == 0} { ::lvfgv::die "no corner defined" }
    }

    lassign [::lvfgv::read_netlist $::lvfgv::cfg(netlist)] order sub
    set cmds {}
    set plan {}   ;# list of {cell arcname states resmap devs}
    set devrows {}
    foreach cell $cells {
        set sname [::lvfgv::find_subckt $sub $cell]
        set devs [::lvfgv::cell_devices $sub $sname]
        if {[llength $devs] == 0} { ::lvfgv::die "cell $cell: no device matched cfg(group_map)" }
        lassign [::lvfgv::instrument_netlist $order $sub $sname $devs] subtext params
        set ports [dict get $sub $sname ports]
        foreach dev $devs {
            set smv [::lvfgv::mismatch_sigma $dev vth]
            set smu [::lvfgv::mismatch_sigma $dev u0]
            if {$smv ne ""} { set smv [::lvfgv::fnum $smv] }
            if {$smu ne ""} { set smu [::lvfgv::fnum $smu] }
            lappend devrows [list $cell [dict get $dev inst] [dict get $dev model] [dict get $dev group] \
                [::lvfgv::fnum [dict get $dev w]] [::lvfgv::fnum [dict get $dev l]] \
                [dict get $dev nf] [dict get $dev m] $smv $smu]
        }
        ::lvfgv::msg "cell $cell: [llength $devs] devices ([join [lmap d $devs {string cat [dict get $d inst] : [dict get $d group]}] { }])"
        foreach arc $::lvfgv::cfg(arcs,$cell) {
            if {$mode eq "sens"} {
                set states [sens_states $devs]
            } else {
                set states [list [list nominal [dict create] "" "" "" 0]]
                foreach cn $cnames {
                    set shifts [::lvfgv::corner_shifts $cn]
                    lappend states [list "corner_$cn" [corner_state $devs $shifts] $cn "" "" 0]
                }
            }
            set resmap [gen_states $cell $arc $states $subtext $params $ports cmds]
            lappend plan [list $cell [dict get $arc name] $states $resmap $devs]
        }
    }
    write_run_script [file join $outdir "run_$mode.sh"] $cmds
    ::lvfgv::msg "[llength $cmds] decks written under $outdir/decks"
    if {[dict get $opt gen_only]} {
        ::lvfgv::msg "gen_only: run $outdir/run_$mode.sh then re-run with -skip_sim"
        return
    }
    if {![dict get $opt skip_sim]} {
        set failed [::lvfgv::run_jobs $cmds $::lvfgv::cfg(jobs)]
        foreach f $failed { ::lvfgv::msg "simulator returned error: [lindex $f 0] :: [lindex $f 1]" }
    }

    # ---- parse and build tables
    set sens_rows {}
    set nom_rows {}
    set cor_rows {}
    set nmissing 0
    set nslew [llength $::lvfgv::cfg(slews)]
    set nload [llength $::lvfgv::cfg(loads)]
    foreach pl $plan {
        lassign $pl cell arcname states resmap devs
        set R [dict create]
        dict for {sn res} $resmap {
            dict set R $sn [read_point_results $res]
        }
        set nom [dict get $R nominal]
        set sigmm [dict create]
        foreach dev $devs {
            foreach p $::lvfgv::cfg(params) {
                set sm [::lvfgv::mismatch_sigma $dev $p]
                if {$sm ne ""} { set sm [::lvfgv::fnum $sm] }
                dict set sigmm "[dict get $dev inst],$p" $sm
            }
        }
        for {set j 0} {$j < $nslew} {incr j} {
            set slew [lindex $::lvfgv::cfg(slews) $j]
            for {set k 0} {$k < $nload} {incr k} {
                set load [lindex $::lvfgv::cfg(loads) $k]
                foreach meas {delay trans} {
                    set v0 [dict get $nom "$meas,$j,$k"]
                    if {$v0 eq ""} { incr nmissing }
                    lappend nom_rows [list $cell $arcname $meas $j $k [::lvfgv::fnum $slew] [::lvfgv::fnum $load] $v0]
                    if {$mode eq "sens"} {
                        # pair +/- states per (inst,param)
                        set pairs [dict create]
                        foreach st $states {
                            lassign $st sn ps inst grp p sign
                            if {$inst eq ""} { continue }
                            dict set pairs "$inst\t$grp\t$p" $sign [dict get $R $sn "$meas,$j,$k"]
                        }
                        dict for {key pm} $pairs {
                            lassign [split $key \t] inst grp p
                            set vp [expr {[dict exists $pm 1]  ? [dict get $pm 1]  : ""}]
                            set vm [expr {[dict exists $pm -1] ? [dict get $pm -1] : ""}]
                            set delta $::lvfgv::cfg(delta,$p)
                            set s1 ""; set s2 ""
                            if {$v0 ne "" && $vp ne "" && $vm ne ""} {
                                set s1 [::lvfgv::fnum [expr {($vp - $vm) / (2.0 * $delta)}]]
                                set s2 [::lvfgv::fnum [expr {($vp - 2.0*$v0 + $vm) / ($delta * $delta)}]]
                            } else {
                                incr nmissing
                            }
                            set sm ""
                            if {[dict exists $sigmm "$inst,$p"]} { set sm [dict get $sigmm "$inst,$p"] }
                            lappend sens_rows [list $cell $arcname $meas $j $k [::lvfgv::fnum $slew] [::lvfgv::fnum $load] \
                                $inst $grp $p $delta $sm $v0 $vp $vm $s1 $s2]
                        }
                    } else {
                        foreach st $states {
                            lassign $st sn ps cn
                            if {$cn eq ""} { continue }
                            set vs [dict get $R $sn "$meas,$j,$k"]
                            set dv ""; set dvr ""
                            if {$v0 ne "" && $vs ne ""} {
                                set dv  [::lvfgv::fnum [expr {$vs - $v0}]]
                                set dvr [::lvfgv::fnum [expr {$v0 != 0 ? ($vs - $v0) / $v0 : 0.0}]]
                            } else {
                                incr nmissing
                            }
                            lappend cor_rows [list $cell $arcname $meas $j $k [::lvfgv::fnum $slew] [::lvfgv::fnum $load] \
                                $cn $v0 $vs $dv $dvr]
                        }
                    }
                }
            }
        }
    }
    if {$nmissing > 0} { ::lvfgv::msg "WARNING: $nmissing measure values missing (check simulator logs)" }
    if {$mode eq "sens"} {
        ::lvfgv::csv_write [file join $outdir sens.csv] $sens_header $sens_rows
        ::lvfgv::csv_write [file join $outdir nominal.csv] $nom_header $nom_rows
        ::lvfgv::csv_write [file join $outdir devices.csv] $dev_header $devrows
        ::lvfgv::msg "wrote $outdir/sens.csv ([llength $sens_rows] rows), nominal.csv, devices.csv"
    } else {
        foreach cn $cnames {
            set rows {}
            foreach r $cor_rows { if {[lindex $r 7] eq $cn} { lappend rows $r } }
            ::lvfgv::csv_write [file join $outdir "corner_$cn.csv"] $cor_header $rows
            ::lvfgv::msg "wrote $outdir/corner_$cn.csv ([llength $rows] rows)"
        }
    }
}

::tsc::main $argv
